enum DekoCode : byte {
	DEKO_LEDON = 0xEC,
	DEKO_LEDOFF = 0xED,
	DEKO_LEDBLINK = 0xE8,
	DEKO_ALLEXTRALEDOFF = 0xEB,
	DEKO_LCDCURSORPOS = 0xE5,
	DEKO_LCDCHAROUT = 0xE6,
	DEKO_LCDCHAROUTEXT = 0xE7,
	DEKO_LCDINSTRUCT = 0xE4,
	DEKO_LEDMASK = 0xED,
};
